version: '2'
services:
    thea-app:
        image: thea
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://thea-mysql:3306/thea?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    thea-mysql:
        extends:
            file: mysql.yml
            service: thea-mysql
